/**
 * The orders API allows you to create, view, update, and delete individual, or a batch, of orders.
 * API for accessing ContosoCMS Order microservice
 *
 * OpenAPI spec version: 1.0.4
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package CMSOrders.model

import play.api.libs.json._

case class Attendee (
                  email: String,
                  firstName: Option[String],
                  lastName: Option[String],
                  seatNumber: Option[Int]
)
{

}
object Attendee {
implicit val format: Format[Attendee] = Json.format
}

